import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'

// initializing the fonts here
const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['300', '600', '800'],
  display: 'swap',
  variable: '--font-nunito-sans',
})

// initializing the metadata here
export const metadata: Metadata = {
  title: 'REST Countries API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${nunito_sans.variable}`}>
      <body className='bg-REST-very-light-gray'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
